-- AlterTable
ALTER TABLE `Patient` ADD COLUMN `userId` INTEGER NULL;

-- AlterTable
ALTER TABLE `User` MODIFY `role` ENUM('ADMIN', 'DOCTOR', 'REGISTRATOR', 'NURSE', 'PATIENT') NOT NULL DEFAULT 'DOCTOR';

-- AddForeignKey
ALTER TABLE `Patient` ADD CONSTRAINT `Patient_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `User`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
